Repository institutoazmina/penhas-app, pull requests merged in 2024-12, with the labels that each got.

#280 Substituir flatButton por penhasButton audios_page
  lib/app/features/help_center/presentation/audios/audios_page.dart
Labels: refactor

#281 Remoção de Operador Null-Safety Desnecessário guardians_page
  lib/app/features/help_center/presentation/guardians/guardians_page.dart
Labels: refactor

#286 Substituição de `RaisedButton` por `PenhasButton` deleted_accoun_page
  lib/app/features/authentication/presentation/deleted_account/deleted_account_page.dart
  test/app/features/authentication/presentation/deleted_account/goldens/ci/deleted_account_page.png
Labels: refactor

#288 Substituição de `RaisedButton` por `PenhasButton` no `chat_channel_message_composer.dart`
  lib/app/features/chat/presentation/pages/channel/chat_channel_message_composer.dart
Labels: refactor

#289 Substituição de `RaisedButton` por `PenhasButton` no `chat_people_filter_card.dart`
  lib/app/features/chat/presentation/pages/chat_people_filter_card.dart
Labels: refactor

#279 [Refatoração] Ajustes no Gerenciamento de Áudio e Downgrade do flutter_sound
  CHANGELOG.md
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/app/core/managers/audio_play_services.dart
  lib/app/core/managers/audio_record_services.dart
  pubspec.lock
  pubspec.yaml
  test/app/core/managers/audio_play_services_test.dart
  test/app/core/managers/audio_record_services_test.dart
Labels: bugfix

#287 Substituição de `RaisedButton` por `PenhasButton` no `LoginButton`
  lib/app/features/authentication/presentation/shared/login_button.dart
  test/app/features/authentication/presentation/shared/goldens/ci/authentication_shared_login_button.png
  test/app/features/authentication/presentation/sign_in/goldens/ci/sign_in_page.png
  test/app/features/authentication/presentation/sign_in_anonymous/goldens/ci/sign_in_anonymous_page.png
  test/app/features/authentication/presentation/sign_in_stealth/goldens/ci/sign_in_stealth_page.png
Labels: refactor

#295 Substitui validação de CPF com `cpfcnpj` por implementação própria e remove dependência
  lib/app/features/authentication/domain/usecases/cpf.dart
  pubspec.lock
  pubspec.yaml
  test/app/features/authentication/domain/usecases/cpf_test.dart
Labels: enhancement, dependencies, deprecation

#296 Substituição de `RaisedButton` por `PenhasButton` no `reset_password_three_page.dart`
  lib/app/features/authentication/presentation/reset_password/pages/reset_password_three/reset_password_three_page.dart
  test/app/features/authentication/presentation/reset_password/pages/reset_password_three/goldens/ci/reset_password_page_step_3.png
Labels: deprecation, refactor

#297 Substituição de `RaisedButton` por `PenhasButton` no `reset_password_page.dart`
  lib/app/features/authentication/presentation/reset_password/reset_password_page.dart
  test/app/features/authentication/presentation/reset_password/goldens/ci/reset_password_page_step_1.png
Labels: deprecation, refactor

#300 Adiciona suporte a estados desabilitados nos estilos de botão e amplia cobertura de testes
  lib/app/shared/design_system/styles/penhas_colors.dart
  lib/app/shared/design_system/widgets/buttons/styles/filled_button_style.dart
  lib/app/shared/design_system/widgets/buttons/styles/rounded_filled_button_style.dart
  lib/app/shared/design_system/widgets/buttons/styles/rounded_outlined_button_style.dart
  lib/app/shared/design_system/widgets/buttons/styles/text_button_style.dart
  test/app/shared/design_system/widgets/buttons/goldens/ci/penhas_button.png
  test/app/shared/design_system/widgets/buttons/penhas_button_test.dart
Labels: bug

#274 Substituir RaisedButton por PenhasButton na página de compose_tweet_page
  lib/app/features/feed/presentation/compose_tweet/compose_tweet_page.dart
  test/app/features/feed/presentation/compose_tweet/goldens/ci/compose_tweet_page.png
  test/app/features/feed/presentation/compose_tweet/goldens/ci/compose_tweet_page_with_app_bar.png
  test/app/features/feed/presentation/compose_tweet/goldens/ci/compose_tweet_page_with_error.png
  test/app/features/feed/presentation/compose_tweet/goldens/ci/compose_tweet_page_with_text.png
Labels: refactor

#278 Substituir RaisedButton por PenhasButton e remover operador nullo reply_tweet_page.dart
  lib/app/features/feed/presentation/reply_tweet/reply_tweet_page.dart
Labels: refactor

#298 Substituir RaisedButton por PenhasButton `feed_category_filter.dart`
  lib/app/features/feed/presentation/pages/feed_category_filter.dart
Labels: deprecation, refactor

#299 Substituir RaisedButton por PenhasButton `feed_tags_filter.dart`
  lib/app/features/feed/presentation/pages/feed_tags_filter.dart
Labels: deprecation, refactor
