Repository institutoazmina/penhas-app, pull requests merged in 2024-11, with the labels that each got.

#129 Design System para botões da App
  lib/app/shared/design_system/styles/penhas_colors.dart
  lib/app/shared/design_system/styles/penhas_text_style.dart
  lib/app/shared/design_system/widgets/buttons/penhas_button.dart
  lib/app/shared/design_system/widgets/buttons/styles/filled_button_style.dart
  lib/app/shared/design_system/widgets/buttons/styles/rounded_filled_button_style.dart
  lib/app/shared/design_system/widgets/buttons/styles/rounded_outlined_button_style.dart
  lib/app/shared/design_system/widgets/buttons/styles/text_button_style.dart
  pubspec.yaml
  test/app/shared/design_system/styles/goldens/ci/penhas_text_style.png
  test/app/shared/design_system/styles/penhas_text_style_test.dart
  test/app/shared/design_system/widgets/buttons/goldens/ci/penhas_button.png
  test/app/shared/design_system/widgets/buttons/penhas_button_test.dart
Labels: enhancement

#266 Renomeia referencias de "new_quiz" para "quiz"
  lib/app/features/quiz/presentation/quiz/messages/_message.dart
  lib/app/features/quiz/presentation/quiz/messages/choices_box.dart
  lib/app/features/quiz/presentation/quiz/messages/horizontal_buttons.dart
  lib/app/features/quiz/presentation/quiz/messages/multiple_choices.dart
  lib/app/features/quiz/presentation/quiz/messages/single_choice.dart
  lib/app/features/quiz/presentation/quiz/messages/text.dart
  lib/app/features/quiz/presentation/quiz/quiz_controller.dart
  lib/app/features/quiz/presentation/quiz/quiz_controller.g.dart
  lib/app/features/quiz/presentation/quiz/quiz_page.dart
  lib/app/features/quiz/quiz_module.dart
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_button_received.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_button_replyed.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_displayTextResponse_received.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_displayText_received.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_empty_state.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_error_state.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_error_state_retry.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_horizontalButtons_received.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_horizontalButtons_replyed.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_multipleChoices_received.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_multipleChoices_replyed.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_received_many_messages.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_scroll_to_end.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_showHelpTutorial_received.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_showHelpTutorial_replyed.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_showStealthTutorial_received.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_showStealthTutorial_replyed.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_singleChoice_received.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_singleChoice_replyed.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_yesno_received.png
  test/app/features/quiz/presentation/quiz/goldens/ci/quiz_yesno_replyed.png
  test/app/features/quiz/presentation/quiz/quiz_page_test.dart
  test/app/features/quiz/presentation/quiz_test_helper.dart
  test/app/features/quiz/quiz_module_test.dart
Labels: refactor

#270 Refatoração do SignInPage para Utilizar o PenhasButton
  lib/app/features/authentication/presentation/sign_in/sign_in_page.dart
  test/app/features/authentication/presentation/sign_in/goldens/ci/sign_in_page.png
Labels: deprecation, refactor

#268 Refatoração do `SignInAnonymousPage` para Utilizar o `PenhasButton`
  lib/app/features/authentication/presentation/sign_in_anonymous/sign_in_anonymous_page.dart
  test/app/features/authentication/presentation/sign_in_anonymous/goldens/ci/sign_in_anonymous_page.png
Labels: deprecation, refactor

#267 Refatoração: Substituição de `RaisedButton` por `PenhasButton.roundedFilled`
  lib/app/features/authentication/presentation/reset_password/pages/reset_password_two/reset_password_two_page.dart
  test/app/features/authentication/presentation/reset_password/pages/reset_password_two/goldens/ci/reset_password_page_step_2.png
Labels: deprecation, refactor

#272 Substituir RaisedButton por PenhasButton na página sign_up_page
  lib/app/features/authentication/presentation/sign_in/sign_up/sign_up_page.dart
  test/app/features/authentication/presentation/sign_in/sign_up/goldens/ci/sign_up_step_1_page.png
Labels: refactor

#273 Substituir botão RaisedButton por PenhasButton na página Categorias de Tweets
  lib/app/features/feed/presentation/category_tweet/category_tweet_page.dart
Labels: refactor

#275 Remover operador nulo condicional obsoleto em detail_tweet_page
  lib/app/features/feed/presentation/detail_tweet/detail_tweet_page.dart
Labels: refactor

#276 Remover operador nulo condicional em feed_page
  lib/app/features/feed/presentation/feed_page.dart
Labels: refactor

#277 Substituir Botões na FilterTweetPage e remover operador nullo
  lib/app/features/feed/presentation/filter_tweet/filter_tweet_page.dart
Labels: refactor
