Repository institutoazmina/penhas-app, pull requests merged in 2025-01, with the labels that each got.

#302 [refactor] Remoção da dependência `flutter_launcher_name` e ajustes relacionados
  ios/Gemfile.lock
  ios/Podfile.lock
  penhas.code-workspace
  pubspec.lock
  pubspec.yaml
Labels: dependencies, deprecation, refactor

#306 [refactor] substituir RaisedButton por PenhasButton na SignUpThreePage
  lib/app/features/authentication/presentation/sign_in/sign_up/pages/sign_up_three/sign_up_three_page.dart
  test/app/features/authentication/presentation/sign_in/sign_up/pages/sign_up_three/goldens/ci/sign_up_step_3_page.png
Labels: deprecation, refactor

#307 Corrigir erro de digitação 'passord' para 'password'
  lib/app/features/authentication/presentation/reset_password/pages/reset_password_three/reset_password_three_page.dart
  lib/app/features/authentication/presentation/shared/password_text_input.dart
  lib/app/features/authentication/presentation/sign_in/sign_in_page.dart
  lib/app/features/authentication/presentation/sign_in/sign_up/pages/sign_up_three/sign_up_three_page.dart
  lib/app/features/authentication/presentation/sign_in_anonymous/sign_in_anonymous_page.dart
  lib/app/features/authentication/presentation/sign_in_stealth/sign_in_stealth_page.dart
  test/app/features/authentication/presentation/shared/password_text_input_test.dart
  test/utils/widget_test_steps.dart
Labels: refactor

#308 Substituição de FlatButton por PenhasButton.text no `tweet_controller.dart`
  lib/app/features/feed/presentation/stores/tweet_controller.dart
Labels: refactor

#309 Substituir webViewJs descontinuado `tweet_body.dart`
  lib/app/features/feed/presentation/tweet/widgets/tweet_body.dart
Labels: refactor

#313 Corrigir acento de Ínicio para Início
  lib/app/features/mainboard/presentation/mainboard/pages/mainboard_button_page.dart
Labels: bugfix

#318 refactor(quiz): simplificar _FilledButton removendo a propriedade width
  lib/app/features/quiz/presentation/quiz/messages/horizontal_buttons.dart
Labels: refactor

#328 [Fix] Corrigir texto de Usuários para Usuárias `profile_edit_page.dart`
  lib/app/features/main_menu/presentation/account/my_profile/profile_edit_page.dart
Labels: bugfix

#377 [refactor] Refatoração e correções na `GuardianTutorialPage`
  lib/app/features/help_center/presentation/pages/tutorial/guardian/guardian_tutorial_page.dart
  test/app/features/help_center/presentation/pages/tutorial/guardian/goldens/ci/guardian_tutorial_page.png
  test/app/features/help_center/presentation/pages/tutorial/guardian/guardian_tutorial_page_test.dart
Labels: deprecation, refactor

#378 refactor: remover dependência do Modular na DeletedAccountPage
  lib/app/app_module.dart
  lib/app/features/authentication/presentation/deleted_account/deleted_account_page.dart
  test/app/features/authentication/presentation/deleted_account/deleted_account_page_test.dart
Labels: dependencies, refactor

#380 Refactor Remover dependencias do Modular `AudioRecordPage`
  lib/app/features/help_center/presentation/pages/audio/audio_record_page.dart
  lib/app/features/mainboard/presentation/mainboard/mainboard_module.dart
Labels: deprecation, refactor

#382 Refactor Remover dependencias do Modular `CategoryTweetPage`
  lib/app/features/feed/presentation/category_tweet/category_tweet_page.dart
  lib/app/features/mainboard/presentation/mainboard/mainboard_module.dart
  test/app/features/feed/presentation/category_tweet/category_tweet_page_test.dart
  test/app/features/feed/presentation/category_tweet/goldens/ci/category_tweet_page.png
Labels: deprecation, refactor

#391 [refactor] Remover dependência do Modular `ChatPage`
  lib/app/features/chat/presentation/chat/chat_channel_page.dart
  lib/app/features/mainboard/presentation/mainboard/mainboard_module.dart
Labels: deprecation, refactor

#392 [Refactor] Remover dependência do Modular `ChatMainPage`
  lib/app/features/chat/presentation/chat_main_module.dart
  lib/app/features/chat/presentation/chat_main_page.dart
Labels: deprecation, refactor

#393 [Refactor] Remover dependência do Modular `ChatMainPeoplePage`
  lib/app/features/chat/presentation/chat_main_module.dart
  lib/app/features/chat/presentation/chat_main_page.dart
  lib/app/features/chat/presentation/people/chat_main_people_page.dart
Labels: deprecation, refactor

#399 [Refactor] Alteração para Injeção Explícita no `DetailTweetPage`
  lib/app/features/feed/presentation/detail_tweet/detail_tweet_page.dart
  lib/app/features/mainboard/presentation/mainboard/mainboard_module.dart
Labels: deprecation, refactor

#395 [Refactor] Remover dependência do Modular `ChatMainTalksPage`
  lib/app/features/chat/presentation/chat_main_module.dart
  lib/app/features/chat/presentation/chat_main_page.dart
  lib/app/features/chat/presentation/talk/chat_main_talks_controller.dart
  lib/app/features/chat/presentation/talk/chat_main_talks_page.dart
  lib/app/features/support_center/presentation/support_center_module.dart
  test/app/features/chat/presentation/talk/chat_main_talks_page_test.dart
Labels: deprecation, refactor
